apiVersion: v1
kind: Service
metadata:
  name: flask-service
  namespace: kendi
spec:
  selector:
    app: flask-app
  ports:
    - protocol: TCP
      port: 52003
      targetPort: 5000
  type: ClusterIP