apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: project2-pvc
  namespace: kendi
spec:
  accessModes: [ReadWriteMany]
  resources:
    requests:
      storage: 1Gi
  selector:
    matchLabels:
      namespace: kendi